### ISSUE TITLE
你好，有问题请教

### ISSUE THREAD

**Issue by heham** [liudongmiao/bootimg#1]
使用脚本打包一个recovery的时候出现问题，下面是解包的内容
base:0x600000
ramdisk_addr:0x4000000
second_addr:0xf00000
tags_addr:0x200000
page_size:0x800
name:
cmdline:vmalloc=384M coherent_pool=512K mem=2044m@0x200000 psci=enable mmcparts=mmcblk0:p1(vrl),p2(vrl_backup),p7(modemnvm_factory),p18(splash),p22(dfx),p23(modemnvm_backup),p24(modemnvm_img),p25(modemnvm_system),p26(modem),p27(modem_dsp),p28(modem_om),p29(modemnvm_update),p31(3rdmodem),p32(3rdmodemnvm),p33(3rdmodemnvmbkp) user_debug=7 androidboot.selinux=enforcing enter_recovery=1 enter_erecovery=0
padding_size:0x800
其中cmdline那个参数按照上面的那个填写打包不会按照那个参数进行，而是按照默认的cmdline参数进行打包，是否bug还是我操作不当？ubuntu32位，python2.7

**Comment by liudongmiao** [comment]
错误提示是啥？完整的命令是啥？

个人建议的是，直接这样，不要加参数。

```
python bootimg.py --unpack-bootimg
python bootimg.py --unpack-ramdisk
```

然后修改以后，执行

```
python bootimg.py --repack-ramdisk
python bootimg.py --repack-bootimg
```

**Comment by liudongmiao** [comment]
突然想了下，cmdline 并不支持从参数传递进去。要改的话，放 bootimg.json 吧。

**Comment by heham** [comment]
谢谢，看来我搞错了，我用的另一个兄弟通过你这个改的win下的程序unpack的，修改后repack不成再用你这个repack就也有问题，刚才试了试直接用你这个在ubuntu下unpack修改后repack一切完好。再次感谢

**Comment by liudongmiao** [comment]
嗯，我不打exe已经很多年了。这个理论上，支持windows/linux/mac的，前提是python环境。

**Comment by heham** [comment]
谢谢，我去更新下，另外我还是习惯转成exe在win下用，如果转发我会注明出处的

**Comment by liudongmiao** [comment]
可以直接使用 pyinstaller 转换，我就不处理了。因为到现在，不支持解包 ext3/ext4，所以对于 system 分区，我连 repack-simg 都没有支持。

**Comment by heham** [comment]
我昨天已经转了的，期待更新支持更多功能，一站式解决方案！
